name: compile-resume
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    env:
      # Edit here with the names of your latex file and directory (can use ".")
      DIR: .
      FILE: resume
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Install TeXlive
        run: sudo apt-get update && sudo apt-get install texlive texlive-full latexmk cm-super
      - name: LaTeX compile
        working-directory: ${{ env.DIR }}
        # Use lualatex instead of pdflatex
        run: |
          latexmk -pdflatex=lualatex -pdf ${{ env.FILE }}
      - name: move
        run: mkdir -p github_artifacts && mv ${{ env.DIR }}/${{ env.FILE }}.pdf ./github_artifacts/
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: ${{ env.FILE }}.pdf
          path: ./github_artifacts
